window.adsColl = [
    {
        "bloque": "1",
        "dimensions": ['fluid',[120,600],[160,600]],
        "dimensions_mobile": [],
        "dispositivo": "desktop",
        "id": "gpt_laterall",
        "id_sitio": 1,
        "islazyload": true,
        "slotName": "elcomercio/web/post/economia/laterall",
        "slotName2": "elcomercio/web/post/economia/laterall",
        "space": "laterall",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "1",
        "dimensions": [[1,1],[970,250],[970,90],[728,90]],
        "dimensions_mobile": [[320,100],[320,50],[300,100],[300,50],[1,1]],
        "dispositivo": "desktop,mobile",
        "id": "gpt_top",
        "id_sitio": 1,
        "islazyload": true,
        "slotName": "elcomercio/web/post/economia/top",
        "slotName2": "elcomercio/web/post/economia/top",
        "space": "top",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "4",
        "dimensions": [[300,600],[300,250],[320,100],[300,100]],
        "dimensions_mobile": [[300,250],[320,100],[300,100]],
        "dispositivo": "desktop",
        "id": "gpt_caja2",
        "id_sitio": 1,
        "islazyload": true,
        "slotName": "elcomercio/web/post/economia/caja2",
        "slotName2": "elcomercio/web/post/economia/caja2",
        "space": "caja2",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "1",
        "dimensions": [[1,1]],
        "dimensions_mobile": [],
        "dispositivo": "desktop",
        "id": "gpt_skin",
        "id_sitio": 1,
        "islazyload": false,
        "slotName": "elcomercio/web/post/economia/skin",
        "slotName2": "elcomercio/web/post/economia/skin",
        "space": "skin",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "1",
        "dimensions": ['fluid',[728,90]],
        "dimensions_mobile": ['fluid',[320,50]],
        "dispositivo": "desktop,mobile",
        "id": "gpt_zocalo",
        "id_sitio": 1,
        "islazyload": false,
        "slotName": "elcomercio/web/post/economia/zocalo",
        "slotName2": "elcomercio/web/post/economia/zocalo",
        "space": "zocalo",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "3",
        "dimensions": [[300,250]],
        "dimensions_mobile": [[300,250],[320,100],[320,50],[300,50],[300,100]],
        "dispositivo": "mobile",
        "id": "gpt_caja3",
        "id_sitio": 1,
        "islazyload": true,
        "slotName": "elcomercio/web/post/economia/caja3",
        "slotName2": "elcomercio/web/post/economia/caja3",
        "space": "caja3",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "1",
        "dimensions": ['fluid',[120,600],[160,600]],
        "dimensions_mobile": [],
        "dispositivo": "desktop",
        "id": "gpt_lateralr",
        "id_sitio": 1,
        "islazyload": false,
        "slotName": "elcomercio/web/post/economia/lateralr",
        "slotName2": "elcomercio/web/post/economia/lateralr",
        "space": "lateralr",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "1",
        "dimensions": ['fluid',[300,250],[300,600],[300,100],[320,100],[300,360]],
        "dimensions_mobile": [],
        "dispositivo": "desktop",
        "id": "gpt_caja1",
        "id_sitio": 1,
        "islazyload": true,
        "slotName": "elcomercio/web/post/economia/caja1",
        "slotName2": "elcomercio/web/post/economia/caja1",
        "space": "caja1",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "3",
        "dimensions": [[1,1],[300,250],[300,190]],
        "dimensions_mobile": [[1,1],[300,250],[300,190]],
        "dispositivo": "desktop,mobile",
        "id": "gpt_inline",
        "id_sitio": 1,
        "islazyload": true,
        "slotName": "elcomercio/web/post/economia/inline",
        "slotName2": "elcomercio/web/post/economia/inline",
        "space": "inline",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "3",
        "dimensions": [[300,250]],
        "dimensions_mobile": [[300,250],[320,100],[320,50],[300,100],[300,50]],
        "dispositivo": "mobile",
        "id": "gpt_caja4",
        "id_sitio": 1,
        "islazyload": true,
        "slotName": "elcomercio/web/post/economia/caja4",
        "slotName2": "elcomercio/web/post/economia/caja4",
        "space": "caja4",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "4",
        "dimensions": [[300,250]],
        "dimensions_mobile": [[300,250],[320,100],[320,50],[300,100],[300,50]],
        "dispositivo": "mobile",
        "id": "gpt_caja5",
        "id_sitio": 1,
        "islazyload": true,
        "slotName": "elcomercio/web/post/economia/caja5",
        "slotName2": "elcomercio/web/post/economia/caja5",
        "space": "caja5",
        "url": "elcomercio/post/economia"
    },
    {
        "bloque": "2",
        "dimensions": [[1,1]],
        "dimensions_mobile": [[1,1]],
        "dispositivo": "desktop,mobile",
        "id": "gpt_vslider",
        "id_sitio": 1,
        "islazyload": false,
        "slotName": "elcomercio/web/post/economia/vslider",
        "slotName2": "elcomercio/web/post/economia/vslider",
        "space": "vslider",
        "url": "elcomercio/post/economia"
    }
]